spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5400/taskmanager
spring.datasource.username=postgres
spring.datasource.password=Kavindra18!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
server.port=8082